#!/bin/sh

currency_pair="$1"
year="$2"
lynx --dump http://www.histdata.com/download-free-forex-historical-data/?/ascii/tick-data-quotes/$currency_pair/$year | awk '/http/{print $2}' | grep $currency_pair > /tmp/file.txt

